### ISSUE TITLE
Package exports for '/Users/XXX/vuecli3-hello-world/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#101]
Run ```npm run serve``` on a newly created vue js project by vue cli 3  (@vue/cli)
```
Module build failed (from ./node_modules/babel-loader/lib/index.js):
Error: [BABEL] /Users/msun/Downloads/dev/vuecli3-hello-world/src/main.js: Package exports for '/Users/msun/Downloads/dev/vuecli3-hello-world/node_modules/@babel/helper-compilation-targets' do not define a '.' subpath (While processing: "/Users/msun/Downloads/dev/vuecli3-hello-world/node_modules/@vue/cli-plugin-babel/preset.js")
    at resolveExports (internal/modules/cjs/loader.js:419:17)
    at Function.Module._findPath (internal/modules/cjs/loader.js:492:20)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:787:27)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/msun/Downloads/dev/vuecli3-hello-world/node_modules/@babel/preset-env/lib/debug.js:8:33)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/msun/Downloads/dev/vuecli3-hello-world/node_modules/@babel/preset-env/lib/index.js:11:14)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)

 @ multi (webpack)-dev-server/client?http://localhost:8080/sockjs-node (webpack)/hot/dev-server.js ./src/main.js
```

**Comment by sunmingtao** [comment]
There is a bug. Need to upgrade to node.js 13.6
https://github.com/babel/babel/issues/10997

```
npm install -g n
sudo n 13.6.0
```
