### ISSUE TITLE
Spring was unable to locate the root of your project. There was no Gemfile present in the current directory

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#115]
Run ```spring init```
Get error
```
Traceback (most recent call last):
	17: from /Users/msun/.rvm/rubies/ruby-2.6.3/bin/spring:23:in `<main>'
	16: from /Users/msun/.rvm/rubies/ruby-2.6.3/bin/spring:23:in `load'
	15: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/bin/spring:49:in `<top (required)>'
	14: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client.rb:30:in `run'
	13: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/command.rb:7:in `call'
	12: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/run.rb:31:in `call'
	11: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/client/run.rb:26:in `connect'
	10: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/env.rb:53:in `socket_name'
	 9: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/env.rb:49:in `socket_path'
	 8: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/env.rb:45:in `application_id'
	 7: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/env.rb:28:in `project_root'
	 6: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/configuration.rb:37:in `project_root_path'
	 5: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/configuration.rb:48:in `find_project_root'
	 4: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/configuration.rb:48:in `find_project_root'
	 3: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/configuration.rb:48:in `find_project_root'
	 2: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/configuration.rb:48:in `find_project_root'
	 1: from /Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/configuration.rb:48:in `find_project_root'
/Users/msun/.rvm/rubies/ruby-2.6.3/lib/ruby/gems/2.6.0/gems/spring-2.1.0/lib/spring/configuration.rb:46:in `find_project_root': Spring was unable to locate the root of your project. There was no Gemfile present in the current directory (/Users/msun/Downloads/dev/scripts) or any of the parent directories. (Spring::UnknownProject)
```

**Comment by sunmingtao** [comment]
This is because there happens to be a ruby gem named spring installed as well.
https://github.com/spring-guides/gs-spring-boot/issues/17

Find out the path to the Spring boot CLI spring command

```which spring```

spring is /Users/msun/.rvm/rubies/ruby-2.6.3/bin/spring
spring is /Users/msun/.sdkman/candidates/springboot/current/bin/spring

Then use the full path of the command

```/Users/msun/.sdkman/candidates/springboot/current/bin/spring --version```

Alternatively,

```
cd /usr/local/bin
sudo ln -sf /Users/msun/.sdkman/candidates/springboot/current/bin/spring ./springboot
```

Then

```springboot --version```
