### ISSUE TITLE
Python unit test: how to generate coverage.xml?

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#13]
Use the coverage html file generated by nosetests+coverage
Run sonar scanner
get error:

```
ERROR: Error during SonarQube Scanner execution
java.lang.IllegalStateException: Error parsing the report '/Users/msun/Downloads/dev/penalty-shootout/cover/index.html'
	at org.sonar.plugins.python.coverage.PythonCoverageSensor.parseReport(PythonCoverageSensor.java:141)
	at org.sonar.plugins.python.coverage.PythonCoverageSensor.execute(PythonCoverageSensor.java:90)
	at org.sonar.scanner.sensor.AbstractSensorWrapper.analyse(AbstractSensorWrapper.java:48)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:85)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.lambda$execute$1(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.withModuleStrategy(ModuleSensorsExecutor.java:77)
	at org.sonar.scanner.sensor.ModuleSensorsExecutor.execute(ModuleSensorsExecutor.java:59)
	at org.sonar.scanner.scan.ModuleScanContainer.doAfterStart(ModuleScanContainer.java:82)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.scan.ProjectScanContainer.scan(ProjectScanContainer.java:359)
	at org.sonar.scanner.scan.ProjectScanContainer.scanRecursively(ProjectScanContainer.java:354)
	at org.sonar.scanner.scan.ProjectScanContainer.doAfterStart(ProjectScanContainer.java:317)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.scanner.bootstrap.GlobalContainer.doAfterStart(GlobalContainer.java:128)
	at org.sonar.core.platform.ComponentContainer.startComponents(ComponentContainer.java:136)
	at org.sonar.core.platform.ComponentContainer.execute(ComponentContainer.java:122)
	at org.sonar.batch.bootstrapper.Batch.doExecute(Batch.java:73)
	at org.sonar.batch.bootstrapper.Batch.execute(Batch.java:67)
	at org.sonarsource.scanner.api.internal.batch.BatchIsolatedLauncher.execute(BatchIsolatedLauncher.java:46)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.base/java.lang.reflect.Method.invoke(Unknown Source)
	at org.sonarsource.scanner.api.internal.IsolatedLauncherProxy.invoke(IsolatedLauncherProxy.java:60)
	at com.sun.proxy.$Proxy0.execute(Unknown Source)
	at org.sonarsource.scanner.api.EmbeddedScanner.doExecute(EmbeddedScanner.java:185)
	at org.sonarsource.scanner.api.EmbeddedScanner.execute(EmbeddedScanner.java:137)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:112)
	at org.sonarsource.scanner.cli.Main.execute(Main.java:75)
	at org.sonarsource.scanner.cli.Main.main(Main.java:61)
Caused by: com.ctc.wstx.exc.WstxParsingException: Unexpected close tag </head>; expected </link>.
 at [row,col {unknown-source}]: [19,6]
	at com.ctc.wstx.sr.StreamScanner.constructWfcException(StreamScanner.java:614)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:487)
	at com.ctc.wstx.sr.StreamScanner.throwParseError(StreamScanner.java:472)
	at com.ctc.wstx.sr.BasicStreamReader.reportWrongEndElem(BasicStreamReader.java:3285)
	at com.ctc.wstx.sr.BasicStreamReader.readEndElem(BasicStreamReader.java:3212)
	at com.ctc.wstx.sr.BasicStreamReader.nextFromTree(BasicStreamReader.java:2831)
	at com.ctc.wstx.sr.BasicStreamReader.next(BasicStreamReader.java:1073)
	at org.codehaus.staxmate.in.SMHierarchicCursor.skipToEndElement(SMHierarchicCursor.java:156)
	at org.codehaus.staxmate.in.SMHierarchicCursor.getNext(SMHierarchicCursor.java:59)
	at org.sonar.plugins.python.coverage.CoberturaParser.lambda$parseReport$0(CoberturaParser.java:61)
	at org.sonar.plugins.python.parser.StaxParser.parse(StaxParser.java:62)
	at org.sonar.plugins.python.parser.StaxParser.parse(StaxParser.java:53)
	at org.sonar.plugins.python.coverage.CoberturaParser.parseReport(CoberturaParser.java:69)
	at org.sonar.plugins.python.coverage.PythonCoverageSensor.parseReport(PythonCoverageSensor.java:137)
	... 31 more
```

**Comment by sunmingtao** [comment]
```nosetests --with-coverage --with-xunit --cover-package=sample
coverage xml
```
