### ISSUE TITLE
ReferencePipeline$2$1.accept(ReferencePipeline.java:176)

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#173]
When executing ```jobDetailsList.stream().filter(JobForm::isValid).collect(Collectors.toList())```, see error

```
java.lang.NullPointerException
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:176)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
```

**Comment by sunmingtao** [comment]
The root cause is ```jobDetailsList``` contains nothing but null elements, causing collect to fail
