### ISSUE TITLE
Fail to open Banjo page: The server time zone value 'AEST' is unrecognized

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#174]
The server is able to start
Connection string already contains `serverTimezone=UTC`

```
2020-08-13 14:08:13:261 +1000 [qtp1160278903-77] ERROR banjo.controllers.ExceptionController - User error with ID: 7fad796a-89f2-42ed-9ae9-85deb4b27a7d - Failed to initialize pool: The server time zone value 'AEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
com.zaxxer.hikari.pool.HikariPool$PoolInitializationException: Failed to initialize pool: The server time zone value 'AEST' is unrecognized or represents more than one time zone. You must configure either the server or JDBC driver (via the 'serverTimezone' configuration property) to use a more specifc time zone value if you want to utilize time zone support.
	at com.zaxxer.hikari.pool.HikariPool.throwPoolInitializationException(HikariPool.java:589)
	at com.zaxxer.hikari.pool.HikariPool.checkFailFast(HikariPool.java:575)
	at com.zaxxer.hikari.pool.HikariPool.<init>(HikariPool.java:115)
	at com.zaxxer.hikari.HikariDataSource.<init>(HikariDataSource.java:81)
	at doss.local.Database.open(Database.java:72)
	at doss.local.Database.open(Database.java:93)
	at doss.local.LocalBlobStore.<init>(LocalBlobStore.java:54)
	at doss.local.LocalBlobStore.open(LocalBlobStore.java:114)
```

**Comment by sunmingtao** [comment]
The issue is amber.path points to a local doss db, which is no longer working with Java 11

`-Damber.path=/Users/msun/data/doss-local`
Changes to a new folder (doesn't have to be existed)

`-Damber.path=/Users/msun/data/doss-new`
