### ISSUE TITLE
java.lang.LinkageError: loader constraint violation: loader 

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#183]
Banjo job can't start
```
Caused by: java.lang.LinkageError: loader constraint violation: loader org.springframework.boot.devtools.restart.classloader.RestartClassLoader @31cf52c0 wants to load class amberdb.AmberSession. A different class with the same name was previously loaded by 'app'. (amberdb.AmberSession is in unnamed module of loader 'app')
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at java.base/java.security.SecureClassLoader.defineClass(SecureClassLoader.java:174)
	at java.base/java.net.URLClassLoader.defineClass(URLClassLoader.java:550)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:458)
	at java.base/java.net.URLClassLoader$1.run(URLClassLoader.java:452)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:451)
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.findClass(RestartClassLoader.java:159)
	at org.springframework.boot.devtools.restart.classloader.RestartClassLoader.loadClass(RestartClassLoader.java:141)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
```

**Comment by sunmingtao** [comment]
Solution:
Ignore amberdb and banjo-common in Intellij and restart banjo job
