### ISSUE TITLE
Unit test error in dl-trove-service

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#184]
Happens on command line only. Works fine in Intellij
```
Running au.gov.nla.dl.services.TroveDetailServiceTest
Tests run: 7, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 3.343 sec <<< FAILURE! - in au.gov.nla.dl.services.TroveDetailServiceTest
returnsBookDetails(au.gov.nla.dl.services.TroveDetailServiceTest)  Time elapsed: 0.5 sec  <<< FAILURE!
java.lang.AssertionError: 
Expected: is <{"responseType":"recordOnly","accessRestrictions":"unrestricted","collection":"nla.aus","contentType":"book","depositType":"depositType","form":"Book","title":"title","creator":"creator","accessAgreement":"accessAgreement","additionalSeriesStatement":"additionalSeriesStatement","alias":["alias"],"bibId":"124","classification":["classification"],"commercialStatus":"Commercial","contributor":["contributor"],"coordinates":["north: north, south: south, east: east, west: west"],"copyright":"copyrightPolicy","creativeCommons":"creativeCommons","creatorStatement":"creatorStatement","edition":"edition","endChild":"endChild","extent":"extent","externalComments":"externalComments","geoAreaCode":["cover"],"holdingNumber":"holdingNumber","isAustralianContent":true,"language":"English","otherTitle":["otherTitle"],"publisher":"publisher","recordSource":"recordSource","recordSourceNumber":"localSystemNumber","rights":"rights","scale":["scale"],"series":["series"],"standardId":["stan"],"startChild":"startChild","subUnitNo":"subUnitNo","subUnitType":"subUnitType","subject":["subject"],"summary":"summary","city":"city","country":"country","province":"province"}>
     but: was <{"responseType":"recordOnly","contentType":"book","form":"Book","accessRestrictions":"unrestricted","collection":"nla.aus","depositType":"depositType","title":"title","creator":"creator","language":"English","rights":"rights","geoAreaCode":["cover"],"isAustralianContent":true,"bibId":"124","standardId":["stan"],"commercialStatus":"Commercial","creatorStatement":"creatorStatement","edition":"edition","summary":"summary","publisher":"publisher","extent":"extent","recordSource":"recordSource","recordSourceNumber":"localSystemNumber","classification":["classification"],"contributor":["contributor"],"series":["series"],"additionalSeriesStatement":"additionalSeriesStatement","subject":["subject"],"copyright":"copyrightPolicy","creativeCommons":"creativeCommons","holdingNumber":"holdingNumber","otherTitle":["otherTitle"],"subUnitNo":"subUnitNo","subUnitType":"subUnitType","sheetName":"sheetName","coordinates":["north: north, south: south, east: east, west: west"],"alias":["alias"],"scale":["scale"],"startChild":"startChild","accessAgreement":"accessAgreement","city":"city","country":"country","province":"province","externalComments":"externalComments","endChild":"endChild"}>
	at org.hamcrest.MatcherAssert.assertThat(MatcherAssert.java:20)
	at org.junit.Assert.assertThat(Assert.java:964)
	at org.junit.Assert.assertThat(Assert.java:930)
	at au.gov.nla.dl.services.TroveDetailServiceTest.returnsBookDetails(TroveDetailServiceTest.java:133)
Running au.gov.nla.dl.services.WorkOcrServiceTest
Tests run: 3, Failures: 0, Errors: 0, Skipped: 1, Time elapsed: 0.013 sec - in au.gov.nla.dl.services.WorkOcrServiceTest
Results :
Failed tests: 
  TroveDetailServiceTest.returnsBookDetails:133
```

**Comment by sunmingtao** [comment]
Observation:

1. Amberdb version 2.26.2-RELEASE works
2. Amberdb version 2.28.0-SNAPSHOT works
3. Amberdb version 2.27.0-SNAPSHOT **doesn't** work on Windows command line, but may work on Mac?
