### ISSUE TITLE
Local Trove vue api fails to start: Access denied for user 'override_in_yaml'@'PC2033.nla.gov.au' 

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#212]
```
Caused by: java.sql.SQLException: Access denied for user 'override_in_yaml'@'PC2033.nla.gov.au' (using password: YES)
	at com.mysql.jdbc.SQLError.createSQLException(SQLError.java:996) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3887) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:3823) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.checkErrorPacket(MysqlIO.java:870) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.proceedHandshakeWithPluggableAuthentication(MysqlIO.java:1659) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.MysqlIO.doHandshake(MysqlIO.java:1206) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.ConnectionImpl.coreConnect(ConnectionImpl.java:2234) ~[mysql-connector-java-5.1.33.jar:5.1.33]
	at com.mysql.jdbc.ConnectionImpl.connectOneTryOnly(ConnectionImpl.java:2265) ~[mysql-connector-java-5.1.33.jar:5.1.33]
```

**Comment by sunmingtao** [comment]
IDE doesn't recognize bash path
```
-Doverride.path=/d/workspace/trove-vue-api/override_ui.yml
```
Change to
```
-Doverride.path=d:/workspace/trove-vue-api/override_ui.yml
```

Note: DO NOT precede the path with `file:`
