### ISSUE TITLE
[webpack-cli] TypeError: CleanWebpackPlugin is not a constructor

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#236]
Import the plugin

`const CleanWebpackPlugin = require('clean-webpack-plugin');`

Running `npm run build` sees error:

```
[webpack-cli] TypeError: CleanWebpackPlugin is not a constructor
    at Object.<anonymous> (/Users/mingtao/workspace/webpack-new/webpack.config.js:46:9)
    at Module._compile (/Users/mingtao/workspace/webpack-new/node_modules/v8-compile-cache/v8-compile-cache.js:192:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19)
```

**Comment by sunmingtao** [comment]
CleanWebpackPlugin is not **default** exported. So it must be imported using curly brackets. 

`const { CleanWebpackPlugin } = require('clean-webpack-plugin');`
