### ISSUE TITLE
Trove admin: Failed to load property source from location 'classpath:/application.groovy'

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#241]
Run `./gradlew bootRun` and get error

```
2020-12-11 17:21:11.308 ERROR --- [           main] o.s.boot.SpringApplication               : Application startup failed

java.lang.IllegalStateException: Failed to load property source from location 'classpath:/application.groovy'
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.loadIntoGroup(ConfigFileApplicationListener.java:476)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:465)
        at org.springframework.boot.context.config.ConfigFileApplicationListener$Loader.load(ConfigFileApplicationListener.java:386)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.addPropertySources(ConfigFileApplicationListener.java:225)
        at org.springframework.boot.context.config.ConfigFileApplicationListener.postProcessEnvironment(ConfigFileApplicationListener.java:195)
```

**Comment by sunmingtao** [comment]
Must run with a profile: `./gradlew -Dgrails.env=local bootRun`
