### ISSUE TITLE
java.sql.SQLException: No suitable driver found for "jdbc:mysql://....."

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#245]
Start trove-admin server

```
Caused by: java.sql.SQLException: No suitable driver found for "jdbc:mysql://mysql-devel.nla.gov.au:6446/newspapers_users?zeroDateTimeBehavior=convertToNull"
	at java.sql.DriverManager.getConnection(DriverManager.java:689)
	at java.sql.DriverManager.getConnection(DriverManager.java:208)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriverManager(DriverManagerDataSource.java:153)
	at org.springframework.jdbc.datasource.DriverManagerDataSource.getConnectionFromDriver(DriverManagerDataSource.java:144)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnectionFromDriver(AbstractDriverBasedDataSource.java:196)
	at org.springframework.jdbc.datasource.AbstractDriverBasedDataSource.getConnection(AbstractDriverBasedDataSource.java:159)
```

**Comment by sunmingtao** [comment]
<img width="922" alt="image" src="https://user-images.githubusercontent.com/2389526/102423863-0e8a9a00-405e-11eb-93ef-ceb8281204bf.png">

DB url shouldn't be wrapped with double quotes
