### ISSUE TITLE
Error scanning entry module-info.class from jar

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#265]
Tim fails to start up with error below
```
11:05:20.647 java[17500]: MultiException[java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/apps/tim/ROOT/WEB-INF/lib/gson-2.8.6.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/apps/tim/ROOT/WEB-INF/lib/istack-commons-runtime-3.0.7.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/apps/tim/ROOT/WEB-INF/lib/txw2-2.3.1.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/apps/tim/ROOT/WEB-INF/lib/stax-ex-1.8.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/apps/tim/ROOT/WEB-INF/lib/FastInfoset-1.2.15.jar, java.lang.RuntimeException: Error scanning entry module-info.class from jar file:/apps/tim/ROOT/WEB-INF/lib/jaxb-runtime-2.3.1.jar]
11:05:20.647 java[17500]:       at org.eclipse.jetty.annotations.AnnotationConfiguration.scanForAnnotations(AnnotationConfiguration.java:535)
11:05:20.647 java[17500]:       at org.eclipse.jetty.annotations.AnnotationConfiguration.configure(AnnotationConfiguration.java:446)
11:05:20.647 java[17500]:       at org.eclipse.jetty.webapp.WebAppContext.configure(WebAppContext.java:473)
11:05:20.647 java[17500]:       at org.eclipse.jetty.webapp.WebAppContext.startContext(WebAppContext.java:1331)
11:05:20.647 java[17500]:       at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:741)
11:05:20.647 java[17500]:       at org.eclipse.jetty.webapp.WebAppContext.doStart(WebAppContext.java:499)
11:05:20.647 java[17500]:       at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:68)
11:05:20.647 java[17500]:       at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:132)
11:05:20.647 java[17500]:       at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114)
```

**Comment by sunmingtao** [comment]
module-info.class is a java 9 feature which requires jetty 9.4.9+

https://stackoverflow.com/questions/45311295/error-scanning-entry-module-info-class-when-starting-jetty-server

The default jetty container in jvmctl is 9.2.5.v20141112

https://github.com/nla/jvmctl/blob/dbfc70d508675aa3c43fa4044fcdfe35e3766cd1/jvmctl/jvmctl/jvmctl.py#L53

The solution is adding to jvmctl node

`JETTY_VERSION=9.4.35.v20201120`
