### ISSUE TITLE
JMockit didn't get initialized

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#341]
Unit tests with JMockit throws error
```
Caused by: java.lang.IllegalStateException: JMockit didn't get initialized; please check the -javaagent JVM initialization parameter was used
	at mockit.internal.startup.Startup.verifyInitialization(Startup.java:91)
	at mockit.MockUp.<clinit>(MockUp.java:53)
	... 70 more
```

**Comment by sunmingtao** [comment]
Add the plugin below to pom.xml
```
<build>
         <plugins>
            <plugin>
                <groupId>org.apache.maven.plugins</groupId>
                <artifactId>maven-surefire-plugin</artifactId>
                <version>2.22.2</version>
                <configuration>
                    <argLine>-javaagent:${settings.localRepository}/org/jmockit/jmockit/${jmockit.version}/jmockit-${jmockit.version}.jar</argLine>\
                    <!-- Excludes integration tests when unit tests are run -->
                    <excludes>
                        <exclude>**/IT*.java</exclude>
                        <exclude>**/selenium/*.java</exclude>
                    </excludes>
                </configuration>
            </plugin>
        </plugins>
    </build>
```
