### ISSUE TITLE
vue js: Exit status 1 at EventEmitter.<anonymous>

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#92]
https://www.udemy.com/course/vuejs-2-the-complete-guide/ Section 10
Download start.zip
Run ```npm run dev```
Get following error

```
0 info it worked if it ends with ok
1 verbose cli [ '/usr/local/bin/node', '/usr/local/bin/npm', 'run', 'dev' ]
2 info using npm@6.12.0
3 info using node@v12.13.0
4 verbose run-script [ 'predev', 'dev', 'postdev' ]
5 info lifecycle vue-cli@~predev: vue-cli@
6 info lifecycle vue-cli@~dev: vue-cli@
7 verbose lifecycle vue-cli@~dev: unsafe-perm in lifecycle true
8 verbose lifecycle vue-cli@~dev: PATH: /usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/node-gyp-bin:/Users/mingtao/Desktop/vuejs/s10/node_modules/.bin:/Users/mingtao/bin:/Users/mingtao/mongo
9 verbose lifecycle vue-cli@~dev: CWD: /Users/mingtao/Desktop/vuejs/s10
10 silly lifecycle vue-cli@~dev: Args: [
10 silly lifecycle   '-c',
10 silly lifecycle   'cross-env NODE_ENV=development webpack-dev-server --open --inline --hot'
10 silly lifecycle ]
11 silly lifecycle vue-cli@~dev: Returned: code: 1  signal: null
12 info lifecycle vue-cli@~dev: Failed to exec dev script
13 verbose stack Error: vue-cli@ dev: `cross-env NODE_ENV=development webpack-dev-server --open --inline --hot`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:210:5)
13 verbose stack     at ChildProcess.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/npm-lifecycle/lib/spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:210:5)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:283:5)
14 verbose pkgid vue-cli@
15 verbose cwd /Users/mingtao/Desktop/vuejs/s10
16 verbose Darwin 18.7.0
17 verbose argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
18 verbose node v12.13.0
19 verbose npm  v6.12.0
20 error code ELIFECYCLE
21 error errno 1
22 error vue-cli@ dev: `cross-env NODE_ENV=development webpack-dev-server --open --inline --hot`
22 error Exit status 1
23 error Failed at the vue-cli@ dev script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]
```

**Comment by sunmingtao** [comment]
https://stackoverflow.com/a/51552111/920554

```npm install -g npm@latest``` to update npm because it is sometimes buggy.
```rm -rf node_modules``` to remove the existing modules.
```npm install``` to re-install the project dependencies.
