### ISSUE TITLE
Error: Cannot find module 'webpack'

### ISSUE THREAD

**Issue by sunmingtao** [sunmingtao/sample-code#99]
Download Mini-App-Finished.zip from https://www.udemy.com/course/vuejs-2-the-complete-guide/learn/lecture/5975876#overview

Run ```npm install``` successfully
Get error:

```
(base) msun-vuejs-s14-finished\ =>npm run dev

> vue-cli@ dev /Users/msun/Downloads/dev/vuejs-s14-finished
> cross-env NODE_ENV=development webpack-dev-server --open --inline --hot

internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module 'webpack'
Require stack:
- /Users/msun/Downloads/dev/vuejs-s14-finished/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/msun/Downloads/dev/vuejs-s14-finished/node_modules/webpack-dev-server/bin/webpack-dev-server.js:12:17)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/msun/Downloads/dev/vuejs-s14-finished/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! vue-cli@ dev: `cross-env NODE_ENV=development webpack-dev-server --open --inline --hot`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the vue-cli@ dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/msun/.npm/_logs/2020-01-24T03_49_23_522Z-debug.log
```

**Comment by sunmingtao** [comment]
Run 
```npm install webpack```
Get error
```
> vue-cli@ dev /Users/msun/Downloads/dev/vuejs-s14-finished
> cross-env NODE_ENV=development webpack-dev-server --open --inline --hot

The CLI moved into a separate package: webpack-cli
Please install 'webpack-cli' in addition to webpack itself to use the CLI
-> When using npm: npm i -D webpack-cli
-> When using yarn: yarn add -D webpack-cli
internal/modules/cjs/loader.js:803
    throw err;
    ^

Error: Cannot find module 'webpack-cli/bin/config-yargs'
Require stack:
- /Users/msun/Downloads/dev/vuejs-s14-finished/node_modules/webpack-dev-server/bin/webpack-dev-server.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:800:15)
    at Function.Module._load (internal/modules/cjs/loader.js:693:27)
    at Module.require (internal/modules/cjs/loader.js:864:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/Users/msun/Downloads/dev/vuejs-s14-finished/node_modules/webpack-dev-server/bin/webpack-dev-server.js:65:1)
    at Module._compile (internal/modules/cjs/loader.js:971:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1011:10)
    at Module.load (internal/modules/cjs/loader.js:822:32)
    at Function.Module._load (internal/modules/cjs/loader.js:730:14)
    at Function.Module.runMain (internal/modules/cjs/loader.js:1051:12) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/Users/msun/Downloads/dev/vuejs-s14-finished/node_modules/webpack-dev-server/bin/webpack-dev-server.js'
  ]
}
```

**Comment by sunmingtao** [comment]
Run
```
npm install --save-dev webpack
npm install --save-dev webpack-dev-server
npm install --save-dev webpack-cli
```

Now ```npm run dev``` gives a blank page. 

```
Entry module not found: Error: Can't resolve 'babel' in '/Users/msun/Downloads/dev/vuejs-s14-finished'
BREAKING CHANGE: It's no longer allowed to omit the '-loader' suffix when using loaders.
                 You need to specify 'babel-loader' instead of 'babel',
                 see https://webpack.js.org/migrate/3/#automatic-loader-module-name-extension-removed
```

**Comment by sunmingtao** [comment]
In ```webpack.config.js```

Change from ```babel``` to ```babel-loader```
```
{
        test: /\.js$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      },
```

Get error

```
ERROR in ./src/main.js
Module build failed (from ./node_modules/babel-loader/lib/index.js):
TypeError: Cannot read property 'babel' of undefined
    at Object.module.exports (/Users/msun/Downloads/dev/vuejs-s14-finished/node_modules/babel-loader/lib/index.js:103:36)
```

**Comment by sunmingtao** [comment]
```npm uninstall babel-loader
npm i -D babel-loader --save-dev```
Still failed. Too many errors.

**Comment by sunmingtao** [comment]
Revert to the original state (Redownload the zip file and unzip it)
Upgrade node js to the latest version (13.7)
```sudo n 13.7.0```
Works like a charm
